# Node.js with Angular

# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- script: |
    cd WebApp
    sudo npm install -g @angular/cli
    npm install
    ng build --prod
  displayName: 'npm install and build'
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'beshoyhanna - Azure'
    appType: 'webApp'
    WebAppName: 'BeshoyHanna'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'